### ISSUE TITLE
When will you release the dataset and  code?

### ISSUE THREAD

**Issue by puppet101** [ChenFengYe/TightCap#1]
Hi, thanks for sharing your great work!  But I find the download link of the dataset is broken, how long will it take to release the dataset and code?

**Comment by ChenFengYe** [comment]
Hi, thank you for your attention! 

At first, we were going to release the dataset with the public download link. However, considering the privacy issue of scanned persons, we change the download form. Please check the page again.

With the email of your request, we will still send you the download link.

**Comment by ChenFengYe** [comment]
After the effort on the privacy issue, we have released all download links. 
You can freely download the dataset from the GitHub page now.

**Comment by puppet101** [comment]
Thank you!
